### ISSUE TITLE
BUG BUG

### ISSUE THREAD

**Issue by heavymetal1** [rshrc/sales-forecast-ml#1]
Yo!

Please read this fully.
Why do you work so hard? Meh, you know very little when compared to others. There are many people in MUJ who know "TON MORE" than you but are still down to earth and humble. All you know is to spit venom and back-bitch 'bout others. You were an awesome guy, but then turned completely around from 2nd year. Not sure what you brag 'bout, but hey, with that attitude, you ain't going anywhere.

Why am I leaving this here? 'Coz you love collaboration right? So I thought Github is best for you! All you care is your reputation and your attitude. If you hate someone, because they are getting ahead of you, you start shitting yourself and start spewing venom on them.

Stay humble, stay down-to-earth and respect others. Don't make people hate you. No wonder people leave confessions for you on Insta. They literally talk about you and your shitty attitude.

Take it as a competition, a healthy one. Don't hate people becoz they know more than you. I know someone who's been very very badly affected by you. You have no idea in what shape he is now. None of us have the courage to confront you, becoz we cannot afford the ruckus you and your gang'd create if you'd know our identities.

Don't take this the wrong way, but I had no other choice. This is just an advice. :)

**Comment by rshrc** [comment]
I will look into this issue for sure, seems critical and very important for your mental stability.
